# Refer https://github.com/zyrouge/web-status-monitor#configuration for documentation
entities:
    - url: "https://google.com"
      method: "get"
    - url: "https://www.stockalpha.in"
      method: "get"
